version: 0.2

phases:
  install:
    commands:
      - echo "Preparing environment..."
  build:
    commands:
      - echo "Packaging portfolio files..."
artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**/*
